//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Location = new HashSet<Location>();
        }
    
        public int ArticleID { get; set; }
        public string ArticleName { get; set; }
        public int CategoryID { get; set; }
        public int GenreID { get; set; }
        public string Duration { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Director { get; set; }
        public double Note { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Location { get; set; }
    }
}
