//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public string Nom_art { get; set; }
        public string Categorie { get; set; }
        public string Genre { get; set; }
        public int Quantite { get; set; }
        public double Prix { get; set; }
        public Nullable<System.DateTime> Date_ajout { get; set; }
    }
}
