//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int FactureID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string CompnayName { get; set; }
        public string CompanyAdDress { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
