//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime Date_de_naissance { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public int Code_Postal { get; set; }
        public string Adresse_de_messagerie { get; set; }
        public string Pseudo { get; set; }
        public string Mot_de_passe { get; set; }
        public string Role { get; set; }
    }
}
