CREATE TABLE [dbo].[Article]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Nom_art] VARCHAR(100) NOT NULL,
	[CategorieID] INT NOT NULL,
	[GenreID] INT NOT NULL,
	[Quantite] INT NOT NULL,
	[Prix] FLOAT NOT NULL,
	[Date_ajout] DATETIME NOT NULL,
	FOREIGN KEY (CategorieID) REFERENCES Categorie(ID),
	FOREIGN KEY (GenreID) REFERENCES Genre(ID)

)
