CREATE TABLE [dbo].[Client]
(
	[CustomerID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Civility] VARCHAR(100) NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	[LastName] VARCHAR(100) NOT NULL,
	[Address] VARCHAR(100) NOT NULL,
	[PostalCode] INT NOT NULL,
	[City] VARCHAR(100) NOT NULL,
	[Phone] INT NOT NULL,
	[Email] VARCHAR(100) NOT NULL,
)
