CREATE TABLE [dbo].[Client]
(
	[CustomerID] INT IDENTITY NOT NULL,
	[IdentityCard] INT NOT NULL,
	[Civility] VARCHAR(MAX) NOT NULL,
	[Name] VARCHAR(MAX) NOT NULL,
	[LastName] VARCHAR(MAX) NOT NULL,
	[BirthDate] DATE NOT NULL,
	[Address] VARCHAR(MAX) NOT NULL,
	[PostalCode] INT NOT NULL,
	[City] VARCHAR(MAX) NOT NULL,
	[Phone] INT NOT NULL,
	[Email] VARCHAR(MAX) NOT NULL,
	PRIMARY KEY (CustomerID)
)
